services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    tty: true
    restart: unless-stopped
    networks:
      - tmdb-net
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    depends_on:
      - ollama
      - tmdb-mcpo
    networks:
      - tmdb-net
    ports:
      - "8080:8080"
    environment:
      - 'WEBUI_SECRET_KEY={WEBUI_SECRET_KEY}'
    volumes:
      - open-webui:/app/backend/data

  tmdb-mcpo:
    build:
      context: .
      dockerfile: Dockerfile.mcpo
    container_name: tmdb-mcpo
    restart: unless-stopped
    networks:
      - tmdb-net
    ports:
      - "8000:8000"
    environment:
      TMDB_API_KEY: ${TMDB_API_KEY}

volumes:
  ollama:
  open-webui:

networks:
   tmdb-net:
